### ISSUE TITLE
tag a release?

### ISSUE THREAD

**Issue by sten0** [jaalto/project-emacs--folding-mode#10]
Hi!

I think folding-mode is past ready for a stable 1.0 tagged release.  Is there any chance you would be willing to tag one?  I maintain the Debian package, and it would make tracking updates much easier.

Thank you,
Nicholas

**Comment by jaalto** [comment]
There are no release schedules for folding.el, I suggest packaging by using date: in format YYYY.MMDD. The date is more informative than a sole number 1.0 for projects that do no update regularly and which do not have specific release goals.
