### ISSUE TITLE
Please specify the version of the GPL this is released under

### ISSUE THREAD

**Issue by tarsius** [jaalto/project-emacs--folding-mode#2]
The permission statement misses the part about the version:

```lisp
;; This program is free software; you can redistribute it and/or
;; modify it under the terms of the GNU General Public License as
;; published by the Free Software Foundation,
;; or (at your option) any later version.
```

This should look like:

```lisp
;; This file is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation; either version N, or (at your option)
;; any later version.
```

(Don't forget to pick a value for `N`.)

Thanks!

**Comment by tarsius** [comment]
Friendly ping!

**Comment by jaalto** [comment]
On 2017-08-04 18:43, Jonas Bernoulli wrote:
| The permission statement misses the part about the version.
| This should look like:
| 
| ```lisp
| ;; This file is free software; you can redistribute it and/or modify
| ;; it under the terms of the GNU General Public License as published by
| ;; the Free Software Foundation; either version N, or (at your option)
| ;; any later version.
| ```

Now updated. Thanks Jonas.

**Comment by tarsius** [comment]
Thanks!
