### ISSUE TITLE
Not working with cpp files properly

### ISSUE THREAD

**Issue by DiogoFerrari** [jaalto/project-emacs--folding-mode#3]
The files .cpp do not fold the regions automatically. I need to call M-x folding-mode when the .cpp is already opened in the buffer. Would you know how to start with the folding-mode on and the regions folded automatically in .cpp files?

**Comment by nega0** [comment]
You can use [File Variables ](https://www.gnu.org/software/emacs/manual/html_node/emacs/File-Variables.html) or [Directory Variables](https://www.gnu.org/software/emacs/manual/html_node/emacs/Directory-Variables.html) to set the variable `folded-file` to `t`. For instance I have this at the top of my `~/.emacs`.
```lisp
;; -*- mode: emacs-lisp; mode: folding; folded-file: t; indent-tabs-mode: nil -*-
;; vim: syntax=lisp: foldmethod=marker
```
Which causes my `~/.emacs` file to be folded when opened for editing. Of course, you have to have `folding-mode` properly set up in your init file too.

**Comment by jaalto** [comment]
The following has been added to the 'Install' section of the documentation
```
(autoload 'turn-on-folding-mode  "folding" "Folding mode" t)

(defun my-folding-mode-activate ()
   (save-excursion
      (goto-char (point-min))
      (when (and (re-search-forward "^.*{{{" nil t)
                 (re-search-forward "^.*}}}" nil t))
         (turn-on-folding-mode))))


(add-hook 'find-file-hook 'my-folding-mode-activate)
```
