### ISSUE TITLE
Full-text copy of GPL-2 (eg: in LICENSE or COPYING) and clarification of one copyright holder.

### ISSUE THREAD

**Issue by sten0** [jaalto/project-emacs--folding-mode#4]
Dear Jari,

Thank you for maintaining folding.el!  The Debian Emacsen team is currently splitting up emacs-goodies-el into a series of elpafied packages, for a variety of reasons.  As a prerequisite to reentry to the archive, folding-mode will probably need to pass through the review process again.  The Debian FTP masters usually require that a full-text copy of a project's license is provided in the upstream sources.  I believe that github can add this using their UI, but here is a link to the GPL-2 in case you'd rather not use their UI:
  https://www.gnu.org/licenses/gpl-2.0.txt

That aside, I suspect that that the following text will block its reentry into the archive: "1992, 1993 Jamie Lokier, _All rights reserved_ [emphasis mine]" for reasons mentioned in this thread:
  https://lists.debian.org/debian-legal/2007/06/msg00251.html
  https://lists.debian.org/debian-legal/2007/06/msg00253.html

Do you know how to contact Jamie Lokier?  From what I've gathered from the thread linked to above, Lokier would need to either remove "All rights reserved", or change it to "All rights not
specifically granted under a licence […] are reserved."

Finally, if necessary, may I quote your replies to this correspondence in the source package's README.source?

Regards,
Nicholas

**Comment by sten0** [comment]
P.S. quoting replies is only necessary if supporting documentation in the repository isn't updated.

**Comment by jlokier** [comment]
Hi Nicholas,

The way to contact me is to wait two years until I accidentally find the issue on a random GitHub search!

Can you point me to which files I should be making changes to?  There is certainly no intention on my part to prevent the normal functioning of the GPL.

One of the messages you linked says: "There was once an international convention that required the phrase for copyright protection to apply.  The convention is no longer relevant.", which seems to be suggesting that it was the correct thing to do at the time of publication, and therefore hard to see why it should become retroactively wrong.

Best,
-- Jamie

**Comment by sten0** [comment]
Hi Jamie!

Jamie Lokier <notifications@github.com> writes:

> Hi Nicholas,
>
> The way to contact me is to wait two years until I accidentally find the issue on a random GitHub search!
>

Haha I'm grateful this worked out :-)

> Can you point me to which files I should be making changes to?  There is certainly no intention on my part to prevent the normal functioning of the GPL.
>

Thanks, much appreciated!  Only two actions are necessary for disambiguation:

1. folding.el
   L8:;; Copyright (C) 1992, 1993 Jamie Lokier, All rights reserved.

   Drop ", All rights reserved" here.

2. And additionally "Add a COPYING file with a copy of the GNU GPL or
   GNU AGPL."  The GNU licensing HOWTO states "Put a license notice in
   each file" but almost nobody does this.  The presence of the
   full-text GPL-2 found at COPYING or LICENSE, plus the GPL boilerplate
   header on the most significant assets (in this case only folding.el
   is required, and it already has the header) is sufficient to indicate
   that the project is 100% GPL-2.  Here's the link again for your
   convenience:

   https://www.gnu.org/licenses/old-licenses/gpl-2.0.txt

IIRC "provide COPYING/LICENSE for multi-file works" is somewhere in one
of the Emacs docs.

Feel free to stop reading here, because the rest of this reply is more
"big picture" stuff that might not interest you ;-)

> One of the messages you linked says: "There was once an international convention that required the phrase for copyright protection to apply.  The convention is no longer relevant.", which seems to be suggesting that it was the correct thing to do at the time of publication, and therefore hard to see why it should become retroactively wrong.
>

As far as I know this convention is specific to the Americas, minus a
couple of notable countries https://en.wikipedia.org/wiki/Buenos_Aires_Convention

I'm not a lawyer, but the courses I've taken on the history of
copyright, and the post ~2007 changes (eg: when photocopying more than a
couple of pages of a book became copyright infringement and "fair use"
began to be more seriously eroded) in laws/treaties, and conversations
with Library Science grads who specialised in copyright convinced me to
be maximally cautious.

I suspect that software might not have been covered by automatic
fixation until 1984, and that the 1979 amendment to the Berne Treaty
addressed this.  IIRC the concept of software as "intellectual property"
didn't really exist until the 70s, but that's just based on what I've
read about the origins of GNU and hacker culture, and how the profit
used to be in the hardware rather than the software.

Given the ambiguity of precedent for "country of origin" (
https://en.wikipedia.org/wiki/Berne_Convention#Country_of_origin ) I
feel like it's especially important for all international projects to be
careful about these things when we might be entering a period of trade
wars and patent litigation.  On this topic, GPL-2+ can automatically
become GPL-3+ for legal purposes, thus patent protection, so there's no
need to explicitly opt into GPL-3+ at this time.  A corporate entity
almost certainly holds a generic patent for a documentation interchange
format that facilitates generation of stylised output (eg:
texi->texinfo), and I believe this is one the reasons for the GNU (and
Debian ftpmaster) recommendation of a COPYING/LICENSE file for
multi-file works, in addition eliminating the tedium of maintaining
copyright headers in each and every file.

The second link also contains

```
> 5) Is it *advisable* to use such a terminology in a copyright statement 
> in a file licensed under the GPL?

No.
```

Would folding.el ever be specifically targeted?  No, almost certainly
not.  As I understand it the most significant existential threat to
FLOSS software would be something like a class-action lawsuit against a
large set of projects conveniently indexed on Github.  Apparently we, as
developers of GPL-2+ software, have some sort of FSF/GNU/SPI legal team
on retainer for such a case.  Cool, no? :-)  eg: we follow the
bureaucratic licensing recommendations, and they promise protection,
thus we don't need to worry about shady patent silos and liabilities and
can work freely on whatever we want to!

Sorry I can't speak to the finer points surrounding "grandfathered"
conventions and the interactions between the Buenos Aires and Berne
Conventions...that's out of my depth and I haven't studied it.

Regards,
Nicholas

**Comment by jaalto** [comment]
Hi Jamie and nice to hear that you're still around, as I am too (occasionally).

Pushed fixes to these:

2020-08-25 18c12c2 jari.aalto mv COPYING LICENSE (HEAD -> master, origin/master, origin/HEAD)
2020-08-25 0dbe0ee jari.aalto COPYING: new
2020-08-25 5d67550 jari.aalto (Docs::Vcs-URL): Chnage from Savannah to Github
2020-08-25 a455704 jari.aalto (Docs): Copyright (C) 1992, 1993 Jamie Lokier [rm: ll rights reserved

Thanks Sten

**Comment by sten0** [comment]
Thank you @jaalto, much appreciated!  P.S. Also, thank you for the VCs-URL fix :-)  I think this issue is resolved, so I'll go head and close it.
