### ISSUE TITLE
Problems with emacs 28 (master)

### ISSUE THREAD

**Issue by ouboub** [jaalto/project-emacs--folding-mode#8]
Hi

I am running emacs master, commit 

Its value is "84ec57fe06e187f41a3546131d5dae3b185c3511"

I downloaded the lastest folding version from melpa
However when starting folding-mode
I receive the following error, 

regards

Uwe Brauer 

Debugger entered--Lisp error: (void-function folding-use-overlays-p)
  (folding-use-overlays-p)
  (cond ((folding-use-overlays-p) (make-local-variable 'line-move-ignore-invisible) (setq line-move-ignore-invisible t buffer-invisibility-spec '((t . t)))) (t (setq selective-display t) (setq selective-display-ellipses t)))
  (if folding-mode (progn (if (null (folding-use-overlays-p)) (setq selective-display nil)) (folding-clear-stack) (folding-narrow-to-region nil nil) (folding-subst-regions (list 1 (point-max)) 13 10) (setq mode-line-format (mapcar #'(lambda (item) (if (equal item ...) "%n" item)) mode-line-format))) (cond ((folding-use-overlays-p) (make-local-variable 'line-move-ignore-invisible) (setq line-move-ignore-invisible t buffer-invisibility-spec '((t . t)))) (t (setq selective-display t) (setq selective-display-ellipses t))) (if (assq 'folding-mode minor-mode-alist) nil (folding-install)) (folding-keep-hooked) (widen) (setq folding-narrow-overlays nil) (folding-set-local-variables) (folding-font-lock-support) (unwind-protect (let ((hook-symbol (intern-soft (concat (symbol-name major-mode) "-folding-hook")))) (run-hooks 'folding-mode-hook) (and hook-symbol (run-hooks hook-symbol))) (folding-set-mode-line)) (and folding-folding-on-startup (if (or (interactive-p) arg inter) (folding-whole-buffer) (save-excursion (folding-whole-buffer)))) (folding-narrow-to-region nil nil t) (setq mode-line-format (mapcar #'(lambda (item) (if (equal item "%n") 'folding-narrow-placeholder item)) mode-line-format)))
  (or (eq new-folding-mode folding-mode) (if folding-mode (progn (if (null (folding-use-overlays-p)) (setq selective-display nil)) (folding-clear-stack) (folding-narrow-to-region nil nil) (folding-subst-regions (list 1 (point-max)) 13 10) (setq mode-line-format (mapcar #'(lambda (item) (if ... "%n" item)) mode-line-format))) (cond ((folding-use-overlays-p) (make-local-variable 'line-move-ignore-invisible) (setq line-move-ignore-invisible t buffer-invisibility-spec '((t . t)))) (t (setq selective-display t) (setq selective-display-ellipses t))) (if (assq 'folding-mode minor-mode-alist) nil (folding-install)) (folding-keep-hooked) (widen) (setq folding-narrow-overlays nil) (folding-set-local-variables) (folding-font-lock-support) (unwind-protect (let ((hook-symbol (intern-soft (concat ... "-folding-hook")))) (run-hooks 'folding-mode-hook) (and hook-symbol (run-hooks hook-symbol))) (folding-set-mode-line)) (and folding-folding-on-startup (if (or (interactive-p) arg inter) (folding-whole-buffer) (save-excursion (folding-whole-buffer)))) (folding-narrow-to-region nil nil t) (setq mode-line-format (mapcar #'(lambda (item) (if (equal item "%n") 'folding-narrow-placeholder item)) mode-line-format))))
  (let ((new-folding-mode (if (not arg) (not folding-mode) (> (prefix-numeric-value arg) 0)))) (or (eq new-folding-mode folding-mode) (if folding-mode (progn (if (null (folding-use-overlays-p)) (setq selective-display nil)) (folding-clear-stack) (folding-narrow-to-region nil nil) (folding-subst-regions (list 1 (point-max)) 13 10) (setq mode-line-format (mapcar #'(lambda ... ...) mode-line-format))) (cond ((folding-use-overlays-p) (make-local-variable 'line-move-ignore-invisible) (setq line-move-ignore-invisible t buffer-invisibility-spec '(...))) (t (setq selective-display t) (setq selective-display-ellipses t))) (if (assq 'folding-mode minor-mode-alist) nil (folding-install)) (folding-keep-hooked) (widen) (setq folding-narrow-overlays nil) (folding-set-local-variables) (folding-font-lock-support) (unwind-protect (let ((hook-symbol (intern-soft ...))) (run-hooks 'folding-mode-hook) (and hook-symbol (run-hooks hook-symbol))) (folding-set-mode-line)) (and folding-folding-on-startup (if (or (interactive-p) arg inter) (folding-whole-buffer) (save-excursion (folding-whole-buffer)))) (folding-narrow-to-region nil nil t) (setq mode-line-format (mapcar #'(lambda (item) (if ... ... item)) mode-line-format)))) (setq folding-mode new-folding-mode) (if folding-mode (easy-menu-add folding-mode-menu) (easy-menu-remove folding-mode-menu)))
  folding-mode()
  funcall-interactively(folding-mode)
  call-interactively(folding-mode nil nil)
  command-execute(folding-mode)

**Comment by jaalto** [comment]
Latest code at Github works ok. Thanks for confirming.
